# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings\settings_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settings_window(object):
    def setupUi(self, settings_window):
        settings_window.setObjectName("settings_window")
        settings_window.resize(437, 539)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(settings_window)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(settings_window)
        self.tabWidget.setObjectName("tabWidget")
        self.setting_tab = QtWidgets.QWidget()
        self.setting_tab.setObjectName("setting_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.setting_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.setting_scrollArea = QtWidgets.QScrollArea(self.setting_tab)
        self.setting_scrollArea.setWidgetResizable(True)
        self.setting_scrollArea.setObjectName("setting_scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 393, 425))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.model_GroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.model_GroupBox.setGeometry(QtCore.QRect(20, 10, 360, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.model_GroupBox.setFont(font)
        self.model_GroupBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.model_GroupBox.setObjectName("model_GroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.model_GroupBox)
        self.formLayout.setObjectName("formLayout")
        self.character_label = QtWidgets.QLabel(self.model_GroupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.character_label.setFont(font)
        self.character_label.setObjectName("character_label")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.character_label
        )
        self.character_comboBox = QtWidgets.QComboBox(self.model_GroupBox)
        self.character_comboBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.character_comboBox.setObjectName("character_comboBox")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.character_comboBox
        )
        self.skin_label = QtWidgets.QLabel(self.model_GroupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.skin_label.setFont(font)
        self.skin_label.setObjectName("skin_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.skin_label)
        self.skin_comboBox = QtWidgets.QComboBox(self.model_GroupBox)
        self.skin_comboBox.setObjectName("skin_comboBox")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.skin_comboBox
        )
        self.action_GroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.action_GroupBox.setGeometry(QtCore.QRect(20, 120, 360, 191))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action_GroupBox.setFont(font)
        self.action_GroupBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.action_GroupBox.setObjectName("action_GroupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.action_GroupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.ifmove_label = QtWidgets.QLabel(self.action_GroupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ifmove_label.setFont(font)
        self.ifmove_label.setObjectName("ifmove_label")
        self.formLayout_2.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.ifmove_label
        )
        self.ifmove_checkBox = QtWidgets.QCheckBox(self.action_GroupBox)
        self.ifmove_checkBox.setText("")
        self.ifmove_checkBox.setObjectName("ifmove_checkBox")
        self.formLayout_2.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.ifmove_checkBox
        )
        self.speed_label = QtWidgets.QLabel(self.action_GroupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.speed_label.setFont(font)
        self.speed_label.setObjectName("speed_label")
        self.formLayout_2.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.speed_label
        )
        self.speed_Slider = QtWidgets.QSlider(self.action_GroupBox)
        self.speed_Slider.setMinimum(1)
        self.speed_Slider.setMaximum(10)
        self.speed_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.speed_Slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.speed_Slider.setTickInterval(1)
        self.speed_Slider.setObjectName("speed_Slider")
        self.formLayout_2.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.speed_Slider
        )
        self.speedprobably_label = QtWidgets.QLabel(self.action_GroupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.speedprobably_label.setFont(font)
        self.speedprobably_label.setObjectName("speedprobably_label")
        self.formLayout_2.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.speedprobably_label
        )
        self.speedprobably_Slider = QtWidgets.QSlider(self.action_GroupBox)
        self.speedprobably_Slider.setMinimum(0)
        self.speedprobably_Slider.setMaximum(100)
        self.speedprobably_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.speedprobably_Slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.speedprobably_Slider.setTickInterval(10)
        self.speedprobably_Slider.setObjectName("speedprobably_Slider")
        self.formLayout_2.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.speedprobably_Slider
        )
        self.minmovetime_label = QtWidgets.QLabel(self.action_GroupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.minmovetime_label.setFont(font)
        self.minmovetime_label.setObjectName("minmovetime_label")
        self.formLayout_2.setWidget(
            3, QtWidgets.QFormLayout.LabelRole, self.minmovetime_label
        )
        self.minmovetime_spinBox = QtWidgets.QSpinBox(self.action_GroupBox)
        self.minmovetime_spinBox.setMinimum(500)
        self.minmovetime_spinBox.setMaximum(20000)
        self.minmovetime_spinBox.setObjectName("minmovetime_spinBox")
        self.formLayout_2.setWidget(
            3, QtWidgets.QFormLayout.FieldRole, self.minmovetime_spinBox
        )
        self.maxmovetime_label = QtWidgets.QLabel(self.action_GroupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.maxmovetime_label.setFont(font)
        self.maxmovetime_label.setObjectName("maxmovetime_label")
        self.formLayout_2.setWidget(
            4, QtWidgets.QFormLayout.LabelRole, self.maxmovetime_label
        )
        self.maxmovetime_spinBox = QtWidgets.QSpinBox(self.action_GroupBox)
        self.maxmovetime_spinBox.setMinimum(1000)
        self.maxmovetime_spinBox.setMaximum(20000)
        self.maxmovetime_spinBox.setProperty("value", 5000)
        self.maxmovetime_spinBox.setObjectName("maxmovetime_spinBox")
        self.formLayout_2.setWidget(
            4, QtWidgets.QFormLayout.FieldRole, self.maxmovetime_spinBox
        )
        self.window_GroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.window_GroupBox.setGeometry(QtCore.QRect(20, 320, 360, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.window_GroupBox.setFont(font)
        self.window_GroupBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.window_GroupBox.setObjectName("window_GroupBox")
        self.formLayout_3 = QtWidgets.QFormLayout(self.window_GroupBox)
        self.formLayout_3.setObjectName("formLayout_3")
        self.size_label = QtWidgets.QLabel(self.window_GroupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.size_label.setFont(font)
        self.size_label.setObjectName("size_label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.size_label)
        self.fps_label = QtWidgets.QLabel(self.window_GroupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.fps_label.setFont(font)
        self.fps_label.setObjectName("fps_label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.fps_label)
        self.fps_spinBox = QtWidgets.QSpinBox(self.window_GroupBox)
        self.fps_spinBox.setMinimum(10)
        self.fps_spinBox.setMaximum(60)
        self.fps_spinBox.setProperty("value", 30)
        self.fps_spinBox.setObjectName("fps_spinBox")
        self.formLayout_3.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.fps_spinBox
        )
        self.size_spinBox = QtWidgets.QSpinBox(self.window_GroupBox)
        self.size_spinBox.setMinimum(100)
        self.size_spinBox.setMaximum(800)
        self.size_spinBox.setProperty("value", 100)
        self.size_spinBox.setObjectName("size_spinBox")
        self.formLayout_3.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.size_spinBox
        )
        self.setting_scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.setting_scrollArea)
        self.button_widget = QtWidgets.QWidget(self.setting_tab)
        self.button_widget.setObjectName("button_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.button_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_Button = QtWidgets.QPushButton(self.button_widget)
        self.save_Button.setObjectName("save_Button")
        self.horizontalLayout.addWidget(self.save_Button)
        self.restore_Button = QtWidgets.QPushButton(self.button_widget)
        self.restore_Button.setObjectName("restore_Button")
        self.horizontalLayout.addWidget(self.restore_Button)
        self.verticalLayout.addWidget(self.button_widget)
        self.tabWidget.addTab(self.setting_tab, "")
        self.plugin_tab = QtWidgets.QWidget()
        self.plugin_tab.setObjectName("plugin_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.plugin_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plugin_scrollArea = QtWidgets.QScrollArea(self.plugin_tab)
        self.plugin_scrollArea.setWidgetResizable(True)
        self.plugin_scrollArea.setObjectName("plugin_scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 393, 473))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.plugin_scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.addWidget(self.plugin_scrollArea)
        self.tabWidget.addTab(self.plugin_tab, "")
        self.verticalLayout_3.addWidget(self.tabWidget)

        self.retranslateUi(settings_window)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(settings_window)

    def retranslateUi(self, settings_window):
        _translate = QtCore.QCoreApplication.translate
        settings_window.setWindowTitle(_translate("settings_window", "桌宠设置"))
        self.model_GroupBox.setTitle(_translate("settings_window", "模型设置"))
        self.character_label.setText(_translate("settings_window", "选择角色:"))
        self.skin_label.setText(_translate("settings_window", "选择皮肤:"))
        self.action_GroupBox.setTitle(_translate("settings_window", "行为设置"))
        self.ifmove_label.setText(_translate("settings_window", "启用移动:"))
        self.speed_label.setText(_translate("settings_window", "移动速度:"))
        self.speedprobably_label.setText(_translate("settings_window", "移动概率:"))
        self.minmovetime_label.setText(_translate("settings_window", "最小移动时长:"))
        self.minmovetime_spinBox.setSuffix(_translate("settings_window", "ms"))
        self.maxmovetime_label.setText(_translate("settings_window", "最大移动时长:"))
        self.maxmovetime_spinBox.setSuffix(_translate("settings_window", "ms"))
        self.window_GroupBox.setTitle(_translate("settings_window", "窗口设置"))
        self.size_label.setText(_translate("settings_window", "桌宠尺寸:"))
        self.fps_label.setText(_translate("settings_window", "动画帧率:"))
        self.fps_spinBox.setSuffix(_translate("settings_window", "fps"))
        self.size_spinBox.setSuffix(_translate("settings_window", "px"))
        self.save_Button.setText(_translate("settings_window", "保存设置"))
        self.restore_Button.setText(_translate("settings_window", "恢复默认"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.setting_tab),
            _translate("settings_window", "设置"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.plugin_tab),
            _translate("settings_window", "插件"),
        )
